# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: tasty-tests
version: '0.0.0'
github: "adriatn-gierakowski/tasty-tests"
license: MIT
author: "adrian gierakowski"
maintainer: "adrian gierakowski"
# synopsis: A new Haskeleton package.
# description: tasty-tests is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  source-dirs: library

executables:
  tasty-tests:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - tasty-tests
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  tasty-tests-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - tasty-tests
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  tasty-tests-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - tasty-tests
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
